Disabled reservation after 10am
Positive-Tech/moja-kuhinjica-FE pull request #64
Opened 2023-05-29 14:30 UTC by Sinisa198

2023-05-29 15:11 UTC, kiljee requested changes

2023-05-29 15:11 UTC, kiljee commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +        console.log("today", today)
remove console.log

2023-05-29 15:11 UTC, kiljee commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +        if (
you can return condition instead `{ return true } else { return false}`

2023-05-30 10:07 UTC, kiljee requested changes

2023-05-30 10:07 UTC, kiljee commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +        const cutoffHour = 10;
move on top` const cutOffHour = 10;`

2023-05-30 10:07 UTC, kiljee commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +        return !(currentHour >= cutoffHour && today.toDateString() === activeDay.toDateString())
currentHour >== cutOffHour 
and can you try different method to compare today and activeDay
try in dayJS

2023-05-30 10:07 UTC, kiljee commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +                                            t(
format this

2023-06-07 15:09 UTC, kiljee approved these changes

2023-06-21 09:24 UTC, kiljee approved these changes

2023-06-21 09:26 UTC, kiljee requested changes

2023-06-21 09:26 UTC, kiljee commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +        const cutoffHour = 10
cutOffHour = 10; 
better naming time before order
also need to be on top file const

2023-06-28 11:50 UTC, vladavoX requested changes

2023-06-28 11:50 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/modal/disabledReservation/DisabledReservationModal.tsx
> +        }
this looks nicer

`if (childer) return childern`

2023-06-28 11:50 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/modal/disabledReservation/DisabledReservationModal.tsx
> +                        {getBody()}
why do we need a function `getBody()`?

we can just render stuff here

```
{childern ? (

) : (

)}
```

2023-06-28 11:50 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +    'Vaša korpa je prazna, ukoliko želite da pogledate svoje rezervacije možete otići na stranicu'
lets create a file in constants folder that has this stuff in it. And just import from there which ones u need, instead of declaring them all here

2023-06-28 11:50 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +        }
`if (!isBookingAllowed()) return setShowDisabledReservation(true)`

2023-06-28 11:50 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +        return !(currentHour >= cutoffHour && today.isSame(activeDay, 'day'))
rewrite this so it returns true based on conditions opposite from one that are here

I guess
`return currentHour <= cutoffHour && !(today.isSame(activeDay, 'day'))`

2023-06-28 11:50 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +                        buttonText={'OK'}
`buttonText='OK'` ?

2023-06-28 11:50 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +                        closeModal={() => setShowDisabledReservation(!true)}
why would we negate `true` where there is `false`
`closeModal={() => setShowDisabledReservation(false)}`

2023-06-28 11:50 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +                                        >
`<Link>` not `router.push`

2023-07-05 08:33 UTC, vladavoX approved these changes

2023-07-05 08:33 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/modal/disabledReservation/DisabledReservationModal.tsx
> +    if (children) return children
we don't need this if

2023-07-05 08:33 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +    'Vaša korpa je prazna, ukoliko želite da pogledate svoje rezervacije možete otići na stranicu'
move these consts to sperate file so we don't clutter this one

2023-07-05 10:18 UTC, vladavoX approved these changes

2023-07-05 13:51 UTC, kiljee approved these changes

2023-07-05 14:12 UTC, merged