Feature/fix bugs with modal reservation
Positive-Tech/moja-kuhinjica-FE pull request #71
Opened 2023-06-05 09:54 UTC by Sinisa198

2023-06-09 08:15 UTC, kiljee requested changes

2023-06-09 08:15 UTC, kiljee commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +    const isBookingAllowed = (): boolean => {
move to helper function 
make code more cleaner and easy to read

2023-06-09 08:15 UTC, kiljee commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
>                                  onClick={() => createOrder()}
onClick={createOrder}

2023-07-05 08:37 UTC, vladavoX approved these changes

2023-07-05 08:37 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/modal/disabledReservation/DisabledReservationModal.tsx
> +    }
remove this function, use conditional rendering

2023-07-05 08:37 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +    'Vaša korpa je prazna, ukoliko želite da pogledate svoje rezervacije možete otići na stranicu'
move these constants to different file

2023-07-05 08:37 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +        }
inline if

2023-07-05 08:37 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +                buttonText={'OK'}
buttonText='OK'

2023-07-05 08:37 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
>                                                  setActiveDate(day.date)
dont use `if - else`

2023-07-05 08:37 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +                                        >
use Link

2023-07-05 13:50 UTC, kiljee approved these changes

2023-07-05 13:50 UTC, merged