Feature/fix translate default language
Positive-Tech/moja-kuhinjica-FE pull request #78
Opened 2023-06-08 09:19 UTC by Sinisa198

2023-06-21 09:31 UTC, kiljee requested changes

2023-06-21 09:31 UTC, kiljee commented on moja-kuhinjica-frontend/src/components/label/ErrorLabel.tsx
> +        const regex = /(.*) email (.*?) (.*?)$/
regex on the top of file

2023-06-21 09:31 UTC, kiljee commented on moja-kuhinjica-frontend/src/components/label/ErrorLabel.tsx
> +        if (matches && matches.length === 4) {
matches?.length is same as matches && matches.length

2023-06-21 09:31 UTC, kiljee commented on moja-kuhinjica-frontend/src/components/label/ErrorLabel.tsx
> +            setBeforeEmail(matches[1])
what is 1?

2023-06-21 09:31 UTC, kiljee commented on moja-kuhinjica-frontend/src/components/label/ErrorLabel.tsx
> +        errorMessage = `${beforeEmail && t(beforeEmail)} ${email} ${
you can write 
const errorMessage = error ? `` : ``

2023-07-05 08:42 UTC, vladavoX approved these changes

2023-07-05 08:42 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/label/ErrorLabel.tsx
> +    const [afterEmail, setAfterEmail] = useState<string>('')
move to single useState

2023-07-05 08:42 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/modal/CanCancelReservation.tsx
> +    }
remove this function, use conditional rendering

2023-07-05 08:42 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/modal/disabledReservation/DisabledReservationModal.tsx
> +    }
remove this function, use conditional rendering

2023-07-05 08:42 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/email/password/[token].tsx
> +    const { t } = useTranslation()
use this `t` to translate

2023-07-05 08:42 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +    'Vaša korpa je prazna, ukoliko želite da pogledate svoje rezervacije možete otići na stranicu'
move them to separate file so they don't clutter this one

2023-07-05 08:42 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +        }
inline if

2023-07-05 08:42 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +                buttonText={'OK'}
buttonText='OK'

2023-07-05 08:42 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
>                                              }
don't use `if - else`

2023-07-05 08:42 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +                                        >
use Link

2023-07-05 08:42 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/myReservations/index.tsx
> +            Nema rezervacija za ovaj datum.
translate this

2023-07-05 13:51 UTC, kiljee approved these changes

2023-07-05 14:12 UTC, merged