Menu item image fixed
Positive-Tech/moja-kuhinjica-FE pull request #91
Opened 2023-06-16 15:10 UTC by NenadM1989

2023-06-21 09:32 UTC, kiljee requested changes

2023-06-21 09:32 UTC, kiljee commented on moja-kuhinjica-frontend/src/styles/components/_menuItem.scss
> +    // margin-bottom: 8%;
delete comments

2023-06-28 19:34 UTC, vladavoX approved these changes

2023-07-05 13:50 UTC, kiljee approved these changes

2023-07-05 13:50 UTC, merged