Feature/remember me
Positive-Tech/moja-kuhinjica-FE pull request #94
Opened 2023-06-26 11:09 UTC by Sinisa198

2023-07-05 05:40 UTC, vladavoX requested changes
Please change the source branch. If you are checking out to a new branch from a certain branch, PR needs to be back in that branch, so I don't see double code that I've already commented

2023-07-05 05:40 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/label/ErrorLabel.tsx
> +            setAfterEmail(matches[3])
I've commented this here
https://github.com/Positive-Tech/moja-kuhinjica-FE/pull/97

2023-07-05 05:40 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/modal/CanCancelReservation.tsx
> +    }
Commented here
https://github.com/Positive-Tech/moja-kuhinjica-FE/pull/97

2023-07-05 05:40 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/modal/CanCancelReservation.tsx
> +                        {getBody()}
Here https://github.com/Positive-Tech/moja-kuhinjica-FE/pull/97

2023-07-05 05:40 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/modal/disabledReservation/DisabledReservationModal.tsx
> +    }
Here https://github.com/Positive-Tech/moja-kuhinjica-FE/pull/97

2023-07-05 05:40 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/modal/disabledReservation/DisabledReservationModal.tsx
> +                        {getBody()}
Here https://github.com/Positive-Tech/moja-kuhinjica-FE/pull/97

2023-07-05 05:40 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/modal/login/LoginModal.tsx
> +                            }}
Here https://github.com/Positive-Tech/moja-kuhinjica-FE/pull/97

2023-07-05 05:40 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/modal/login/LoginModal.tsx
> +                        <p>Zapamti me</p>
Here https://github.com/Positive-Tech/moja-kuhinjica-FE/pull/97

2023-07-05 13:49 UTC, kiljee approved these changes

2023-07-06 05:23 UTC, vladavoX requested changes

2023-07-06 05:23 UTC, vladavoX commented on moja-kuhinjica-frontend/src/components/label/ErrorLabel.tsx
> +    const [afterEmail, setAfterEmail] = useState<string>('')
create single state

2023-07-06 05:23 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/email/password/[token].tsx
> +    const { t } = useTranslation()
use this `t` to translate

2023-07-06 05:23 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/login/index.tsx
> +                            }}
inline `onChange`

2023-07-06 05:23 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/login/index.tsx
> +                        <p>Zapamti me</p>
translate

2023-07-06 05:23 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +    'Vaša korpa je prazna, ukoliko želite da pogledate svoje rezervacije možete otići na stranicu'
move these to seprate file

2023-07-06 05:23 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +        }
write this inline

2023-07-06 05:23 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +                buttonText={'OK'}
buttonText='OK'

2023-07-06 05:23 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
>                                                  setActiveDate(day.date)
dont use `else`, write two `if`s that return

2023-07-06 05:23 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/mealReservation/index.tsx
> +                                        >
use Link

2023-07-06 05:23 UTC, vladavoX commented on moja-kuhinjica-frontend/src/pages/myReservations/index.tsx
> +            Nema rezervacija za ovaj datum.
translate

2023-07-06 08:27 UTC, vladavoX approved these changes

2023-07-06 08:28 UTC, merged